### ISSUE TITLE
Black background on soundplaying tab icon

### ISSUE THREAD

**Issue by BGMP** [BGMP/firefox-revert-proton#5]
This SVG renders differently on Firefox Developer Edition (black circle) and upstream Firefox (actual soundplaying icon).
```css
.tab-icon-overlay[soundplaying] {
	list-style-image: url("chrome://browser/skin/tabbrowser/tab-audio-playing-small.svg");
}
```
This effect causes the following problem on Firefox Developer:

![Capture](https://user-images.githubusercontent.com/26081543/213900368-5a6f6354-fe4e-4326-a637-8cebb0768ffe.PNG)

Will investigate if it becomes an issue in upstream.
